# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=50)),
                ('flat_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('type_occupancy', models.BooleanField()),
                ('apartment_id', models.CharField(max_length=50)),
            ],
        ),
    ]
