# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppartmentName', models.CharField(max_length=50)),
                ('AppartmentEmail', models.CharField(max_length=50)),
                ('AppartmentAddress', models.CharField(max_length=500)),
                ('NoOfBlocks', models.CharField(max_length=10)),
                ('NumberOfFlats', models.CharField(max_length=10)),
                ('EmailAddress', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('LandLine', models.CharField(max_length=15)),
                ('PasswordHash', models.CharField(max_length=50)),
                ('AccountHolderName', models.CharField(max_length=50)),
                ('AccountNumber', models.CharField(max_length=30)),
                ('IFSCCode', models.CharField(max_length=20)),
            ],
        ),
    ]
