# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0002_apartmentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredApartUser',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=50)),
                ('flat_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=50)),
                ('type_occupancy', models.BooleanField()),
                ('have_car', models.BooleanField()),
                ('apartment_id', models.CharField(max_length=50)),
                ('passwordHash', models.CharField(max_length=50)),
                ('otp_hash', models.CharField(max_length=50)),
                ('verified_mobile', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedRegistrations',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=50)),
                ('flat_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=50)),
                ('type_occupancy', models.BooleanField()),
                ('have_car', models.BooleanField()),
                ('apartment_id', models.CharField(max_length=50)),
                ('passwordHash', models.CharField(max_length=50)),
            ],
        ),
    ]
